"""Test script for Part 5 FastAPI backend."""
from fastapi.testclient import TestClient
from part5_api import app

client = TestClient(app)


def test_get_alerts_empty():
    """Test GET /api/alerts returns empty list."""
    resp = client.get("/api/alerts")
    assert resp.status_code == 200
    data = resp.json()
    assert isinstance(data, list)
    print("Test 1 passed: GET /api/alerts returns empty list")


def test_start_stop_simulator():
    """Test simulator start/stop endpoints."""
    # Start simulator
    resp = client.post("/api/simulator/start", json={"duration_sec": 5})
    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "running"
    print("Test 2 passed: Simulator start")

    # Stop simulator
    resp = client.post("/api/simulator/stop")
    assert resp.status_code == 200
    data = resp.json()
    assert data["message"] == "Simulator stopped"
    print("Test 3 passed: Simulator stop")


def test_alert_lifecycle():
    """Test full alert detection -> playbook -> LLM pipeline."""
    from part1_data_simulator import log_stream
    from part5_api import process_log_entry

    # Process logs directly to populate alert_history in sync test context
    for i, entry in enumerate(log_stream(stream_duration_sec=10, inject_attacks=True, sleep_between=False)):
        alert = process_log_entry(entry)
        if alert:
            break

    # Check alerts generated
    resp = client.get("/api/alerts")
    data = resp.json()
    assert len(data) > 0, "No alerts generated by simulator"

    # Check alert structure
    alert = data[0]
    assert "alert_id" in alert
    assert "type" in alert
    assert "severity" in alert
    assert "source_ip" in alert
    assert "timestamp" in alert
    assert "raw_evidence" in alert
    assert "action_taken" in alert
    assert "incident_summary" in alert

    # Check action_taken has required fields
    at = alert["action_taken"]
    assert "action" in at
    assert "target" in at
    assert "timestamp" in at
    assert "status" in at

    print("Test 4 passed: Alert lifecycle works")
    print(f"  Alert type: {alert['type']}")
    print(f"  Severity: {alert['severity']}")
    print(f"  Action: {at['action']} - status: {at['status']}")
    print(f"  Summary: {alert['incident_summary'][:80]}...")


def test_approval_endpoint():
    """Test human analyst approve/override."""
    data = client.get("/api/alerts").json()
    assert len(data) > 0, "No alerts to approve"

    alert_id = data[0]["alert_id"]
    # Test approve
    resp = client.post(
        f"/api/alerts/{alert_id}/approve",
        json={"alert_id": alert_id, "approved": True, "comment": "Looks good"}
    )
    assert resp.status_code == 200
    result = resp.json()
    assert result["decision"]["approved"] == True

    # Test override
    resp = client.post(
        f"/api/alerts/{alert_id}/approve",
        json={"alert_id": alert_id, "approved": False, "comment": "Manual override"}
    )
    assert resp.status_code == 200
    result = resp.json()
    assert result["decision"]["approved"] == False

    print("Test 5 passed: Approve/override endpoint works")


if __name__ == "__main__":
    test_get_alerts_empty()
    test_start_stop_simulator()
    test_alert_lifecycle()
    test_approval_endpoint()
    print("\nAll tests passed!")